import Alligator from "./models/Alligator.js";
import Bear from "./models/Bear.js";
import Cat from "./models/Cat.js";
import Donkey from "./models/Donkey.js";
import Elephant from "./models/Elephant.js";
import Flamingo from "./models/Flamingo.js";
import Giraffe from "./models/Giraffe.js";
import Hippopotamus from "./models/Hippopotamus.js";
import Iguana from "./models/Iguana.js";
import Jaguar from "./models/Jaguar.js";
import Kangaroo from "./models/Kangaroo.js";
import Lion from "./models/Lion.js";
import Macaw from "./models/Macaw.js";
import Newt from "./models/Newt.js";
import Ostrich from "./models/Ostrich.js";
import Pig from "./models/Pig.js";
import Quail from "./models/Quail.js";
import Rhinoceros from "./models/Rhinoceros.js";
import Sheep from "./models/Sheep.js";
import Tiger from "./models/Tiger.js";
import Urial from "./models/Urial.js";
import Vole from "./models/Vole.js";
import Wolf from "./models/Wolf.js";
import XRayTetra from "./models/XRayTetra.js";
import Yak from "./models/Yak.js";
import Zebra from "./models/Zebra.js";

let ally = new Alligator("Ally", "Green", "F", 200, 60, "big");
let smokey = new Bear("Smokey", "Brown", "M", 430, 4, "big");
let kitty = new Cat("Kitty", "Ginger", "F", 18, 8, "small");
let donkey = new Donkey("Donkey", "Greyish-brown", "M", 200, 3.5, "medium");
let dumbo = new Elephant("Dumbo", "Grey", "M", 600, 14, "big");
let flynn = new Flamingo("Flynn", "Pink", "M", 90, 9, "just a beak");
let graham = new Giraffe("Graham", "Orange", "M", 350, 18, "medium");
let hungryHip = new Hippopotamus("Hungry Hip", "Grey", "M", 650, 12, "big");
let elaine = new Iguana("Elaine", "Green", "F", 26, 18, "small");
let jane = new Jaguar("Jane", "Golden-brown-yellow", "F", 80, 14, "big");
let kip = new Kangaroo("Kip", "Brown", "M", 100, 28, "small");
let leo = new Lion("Leo", "Golden-brown", "M", 250, 19, "big");
let maximus = new Macaw("Maximus", "Rainbow-red", "M", 18, 12, "just a beak");
let newton = new Newt("Newton", "Orange-red", "M", 1, 3, "tiny");
let olive = new Ostrich("Olive", "Black-white-pink", "F", 95, 8, "just a beak");
let petrov = new Pig("Petrov", "Pink", "M", 280, 7, "small");
let quinton = new Quail("Quinton", "Brown", "M", 2.5, 5, "just a beak");
let riley = new Rhinoceros("Riley", "Grey", "F", 600, 9, "big");
let shelly = new Sheep("Shelly", "white", "F", 65, 7, "small");
let tyler = new Tiger("Tyler", "Orange-brown", "M", 220, 9, "big");
let umar = new Urial("Umar", "Grey", "M", 200, 7, "medium");
let violet = new Vole("Violet", "Brownish-grey", "F", 3, 5, "tiny");
let whitney = new Wolf("Whitney", "Grey-white", "F", 175, 8, "big");
let xilo = new XRayTetra("Xilo", "Silver", "M", 8, 8, "small");
let yann = new Yak("Yann", "Brown", "M", 450, 15, "big");
let zala = new Zebra("Zaden", "Black-white", "F", 350, 14, "medium");